site_name: 'python-app'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/salva-moyano/mpr-backstage
edit_uri: edit/main/python-app/docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - Getting started: 'index.md'