name: cicd

on:
  push:
    paths:
      - python-app/src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./python-app
          push: true
          tags: salvamoyanopalma/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Modify values file
        shell: bash
        run: | 
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.img.tag = "${{needs.ci.outputs.commit_id}}"' python-app/charts/python-app/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - name: install argocd
        shell: bash
        run: | 
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argo-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
          argocd app sync python-app
        